### ISSUE TITLE
AttributeError when changing a watched page

### ISSUE THREAD

**Issue by marcelofernandez** [trac-hacks/trac-wikinotification#3]
Hi, I'm using Trac with a PostgreSQL backend, and I'm getting this error when changing a watched wiki page:

Trac detected an internal error:
AttributeError: 'WikiNotifyEmail' object has no attribute 'db'

```
Most recent call last:
File "/usr/local/lib/python2.7/dist-packages/trac/web/main.py", line 513, in _dispatch_request
  dispatcher.dispatch(req)
File "/usr/local/lib/python2.7/dist-packages/trac/web/main.py", line 222, in dispatch
  resp = chosen_handler.process_request(req)
File "/usr/local/lib/python2.7/dist-packages/trac/wiki/web_ui.py", line 156, in process_request
  return self._do_save(req, versioned_page)
File "/usr/local/lib/python2.7/dist-packages/trac/wiki/web_ui.py", line 357, in _do_save
  req.remote_addr)
File "/usr/local/lib/python2.7/dist-packages/trac/wiki/model.py", line 169, in save
  comment, author, remote_addr)
File "/usr/local/lib/python2.7/dist-packages/WikiNotification/listener.py", line 42, in wiki_page_changed
  wne.notify("modified", page, version, time, comment, author, ipnr)
File "/usr/local/lib/python2.7/dist-packages/WikiNotification/notification.py", line 147, in notify
  NotifyEmail.notify(self, page.name, subject)
File "/usr/local/lib/python2.7/dist-packages/trac/notification.py", line 365, in notify
  Notify.notify(self, resid)
File "/usr/local/lib/python2.7/dist-packages/trac/notification.py", line 248, in notify
  torcpts, ccrcpts = self.get_recipients(resid)
File "/usr/local/lib/python2.7/dist-packages/WikiNotification/notification.py", line 150, in get_recipients
  if not self.db:
```

I'm using Trac 1.0.4 on Ubuntu 14.04 and PostgreSQL 9.3, connecting through a Unix socket. The wiki-notification section is configured with default values.

Regards

**Comment by mitar** [comment]
Sorry, I am not sure what it could be.

**Comment by marcelofernandez** [comment]
Ok, I'll try to debug the problem. 

Could you throw some hints to me? I don't know anything about Trac plugins.

Thank you

**Comment by mitar** [comment]
Which version of the plugin are you using? Because [line 150](https://github.com/trac-hacks/trac-wikinotification/blob/master/WikiNotification/notification.py#L150) does not have `if not self.db:`?

**Comment by marcelofernandez** [comment]
You're right, seems I've installed an old and different version of the code, comparing what I have in my machine and this github repo.

I've installed the plugin like the README.rst says, "easy_install TracWikiNotification":

```
easy_install TracWikiNotification
/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'python-apt (0.9.3.5ubuntu1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'python-debian (0.1.21-nmu2ubuntu2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
Searching for TracWikiNotification
Reading https://pypi.python.org/simple/TracWikiNotification/
Reading http://python.org/pypi/TracWikiNotification
Reading http://wikinotification.ufsoft.org
Best match: TracWikiNotification 0.2.1
Downloading https://pypi.python.org/packages/source/T/TracWikiNotification/TracWikiNotification-0.2.1.zip#md5=686bcae1eabb115ad23ff17423954b31
Processing TracWikiNotification-0.2.1.zip
Writing /tmp/easy_install-5Rovhi/TracWikiNotification-0.2.1/setup.cfg
Running TracWikiNotification-0.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5Rovhi/TracWikiNotification-0.2.1/egg-dist-tmp-SnIcvF
zip_safe flag not set; analyzing archive contents...
WikiNotification.listener: module MAY be using inspect.stack
creating /usr/local/lib/python2.7/dist-packages/TracWikiNotification-0.2.1-py2.7.egg
Extracting TracWikiNotification-0.2.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding TracWikiNotification 0.2.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/TracWikiNotification-0.2.1-py2.7.egg
Processing dependencies for TracWikiNotification
Finished processing dependencies for TracWikiNotification
```

**Comment by mitar** [comment]
Ah, yes. This is a fork of the project. I do not have permissions on PyPi for TracWikiNotification package. So I cannot release a new version. You will have to install it from the repository. (`setup.py install`)

**Comment by marcelofernandez** [comment]
Oh, ok. I've cloned this repo, executed setup.py build/install and now the plugin is working fine. :-)

Could you please, update the README.rst from this repo so it doesn't point to pypi anymore? (see installation)

Regards

**Comment by rjollos** [comment]
Have you tried contacting the PyPI package owner?  There are a lot of out of date packages for Trac on PyPI.  Eventually I hope to do some research into how we can get these updated our removed,  even in cases that the owner can't be reached.

**Comment by marcelofernandez** [comment]
No, I didn't. Perhaps mentioning him (@s0undt3ch) would work? I can't find Pedro's mail.

The first thing comes to my mind is renaming the extension. "TracWikiNotification2" sounds fine for me, but it's your call, of course. Let's see if Pedro reads this issue.

Regards

**Comment by s0undt3ch** [comment]
I'm no longer maintaining my track plugins. If anyone wants to take the project, I can grant permissions on PyPi so a new release can be made.

**Comment by mitar** [comment]
@s0undt3ch, can you then give me ownership? My username there is "mitar" as well.

**Comment by s0undt3ch** [comment]
Granted!

**Comment by s0undt3ch** [comment]
Let me know if you have issues uploading to PyPi...

**Comment by mitar** [comment]
Interesting. Previously, I get permission denied error. Now, I get "Upload failed (500): Internal Server Error". That is some PyPi bug?

**Comment by mitar** [comment]
I will retry later.

**Comment by s0undt3ch** [comment]
I switched you from maintainer to owner. let's see if that works

**Comment by mitar** [comment]
No difference. I think it is some internal issue.

**Comment by mitar** [comment]
It worked now! It seems just a fluke.

**Comment by mitar** [comment]
0.3 released.

**Comment by s0undt3ch** [comment]
Awesome!

I'll keep you as owner which also allows you to add additional maintainers.

Thank You for keeping the plugin alive!

**Comment by mitar** [comment]
Thank you for making it in the first place.

**Comment by s0undt3ch** [comment]
Hmm, I have the old code with complete history is kept [here](https://github.com/UfSoft/trac-wiki-notification).... Mind grabbing the full history from there and fork it into track-hacks?

**Comment by s0undt3ch** [comment]
I can join both git repos if you prefer...

**Comment by s0undt3ch** [comment]
I merged the history from this repo into mine. How can we make this one a fork?

**Comment by mitar** [comment]
I think I have already full history in this repository?

**Comment by s0undt3ch** [comment]
Yes, but my move from svn to hg and then to git did not include a valid email address from me.

**Comment by mitar** [comment]
I think we will have to delete this repository and then fork yours. This will be a bit complicated with permissions.

**Comment by s0undt3ch** [comment]
I've fixed authorship, forked this repo, merged both, and I'm submitting a PR against this repo.

I'll create a github issue to see if they can solve the "make this one a fork of ..."

**Comment by mitar** [comment]
I don't think a merge can work, because you are rewriting history. I can probably force push it from your repository.

**Comment by s0undt3ch** [comment]
https://github.com/trac-hacks/trac-wikinotification/pull/4

**Comment by s0undt3ch** [comment]
Can't be merged? the PR?

Bummer.

**Comment by mitar** [comment]
I force pushed.

**Comment by s0undt3ch** [comment]
If you're the only one touching this code right now, a force push wouldn't be that bad...

**Comment by mitar** [comment]
It could be merged, but you would still have two lines of development. One without your name, one with it.

**Comment by s0undt3ch** [comment]
Thanks!

**Comment by mitar** [comment]
NP.

**Comment by s0undt3ch** [comment]
Oh?

Yeah, that's better.

**Comment by s0undt3ch** [comment]
OK. We can't simply change this repo into a for(even if its github doing it directly).

Let's keep it as it is since the development is being done here and I won't be touching this code any time soon.

Again, Thank You @mitar for picking up the development if the plugin.

**Comment by s0undt3ch** [comment]
*fork

**Comment by s0undt3ch** [comment]
*of

Dam phone...
