### ISSUE TITLE
Notifications should honour access restrictions

### ISSUE THREAD

**Issue by benzea** [trac-hacks/trac-wikinotification#7]
currently the wiki notification plugin does not honour access restrictions. This means that it is possible for a person to subscribe to a page that he/she cannot read, and they will get change notifications.

Sorry, no proper diff (I just hacked an older plugin):

    # add required imports
    from trac.resource import Resource
    from trac.perm import PermissionSystem
    
    # in get_recipients just replace the loop (i.e. the single "for sid in sids:" line):
            perm = PermissionSystem(self.env)
            for sid in sids:
                if not perm.check_permission(action='WIKI_VIEW', username=sid, resource=Resource('wiki', pagename)):
                    continue

**Comment by mitar** [comment]
Please make this into a pull request.

**Comment by benzea** [comment]
Oh, completely forgot about this. Thanks for making a commit out of it!

**Comment by mitar** [comment]
Thanks for providing code!
